defaults: &defaults
  access_key_id:  "AKIAIEXS5LTCX3X3CSJQ"
  secret_access_key: "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"
development:
  <<: *defaults
  bucket: "rlc-development"
test:
  <<: *defaults
  bucket: "rescuingleftover-test"
staging:
  <<: *defaults
  bucket: "rescuingleftover-staging"
production:
  <<: *defaults
  bucket: "rlc-production"