development:
 adapter: postgresql
 encoding: utf8
 database: calendar_development
 #database: evac_development
 pool: 5

test: &TEST
 adapter: postgresql
 encoding: utf8
 database: calendar_test
 pool: 5
